
/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: "80742061451",
    title: "Traditional Opulent Gold Nath",
    imgSrc : "https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwe3df3fbb/images/hi-res/513018ORMAAAP3_1.jpg?sw=360&sh=360",
    description: "Flaunt your classy side with the help of this link chain, crafted in 22 karat yellow gold",
    price: "₹121395",
    starRating: 4.5,
    category: "Nose pins",
    metalType: "Gold",
    inStock: true,
  },
  {
    _id: "58664694049",
    title: "Single Stoned Diamond Nose Pin",
    imgSrc: "https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwc673676c/images/hi-res/510063ORAAAA02_1.jpg?sw=360&sh=360",
    description: "Flaunt your classy side with the help of this link chain, crafted in 22 karat yellow gold",
    price: "₹10535",
    starRating: 3.5,
    category: "Nose pins",
    metalType: "Gold",
    inStock: true,
  },
  {
    _id: "2511032423",
    title: "Shimmering Petite Diamond Nose Ring",
    imgSrc: "https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw08608316/images/hi-res/502614OCCAAA09_1.jpg?sw=360&sh=360",
    description: "Flaunt your classy side with the help of this link chain, crafted in 22 karat yellow gold",
    price: "₹13120",
    starRating: 3,
    category: "Nose pins",
    metalType: "Diamond",
    inStock: false,
  },
  {
    _id: "10320589950",
    title: "Sublime Diamond Nose Pin",
    imgSrc: "https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw29f9d18f/images/hi-res/501145OAKABA09_1.jpg?sw=360&sh=360",
    description: "Flaunt your classy side with the help of this link chain, crafted in 22 karat yellow gold",
    price: "₹21716",
    starRating: 5,
    category: "Nose pins",
    metalType: "Diamond",
    inStock: false,
  },
  {
    _id: "55425425456",
    title: "Irresistible Floral Diamond Nose Pin",
    imgSrc: "https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw2ae890b6/images/hi-res/500064OGAAAA09_1.jpg?sw=360&sh=360",
    description: "Flaunt your classy side with the help of this link chain, crafted in 22 karat yellow gold",
    price: "₹10064",
    starRating: 4,
    category: "Nose pins",
    metalType: "Diamond",
    inStock: true,
  },
  {
    _id: "86460088185",
    title: "Bold Glint Diamond Ring",
    imgSrc: "https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw9a9e520f/images/hi-res/50D2FFFFKAA02_1.jpg?sw=360&sh=360",
    description: "Flaunt your classy side with the help of this link chain, crafted in 22 karat yellow gold",
    price: "₹32894",
    starRating: 2,
    category: "Finger rings",
    metalType: "Diamond",
    inStock: true,
  },
  {
    _id: "57601234110",
    title: "Spiritual Rudraksh Ring",
    imgSrc: "https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw7faff6d9/images/hi-res/50F2MSFBUAAP1_1.jpg?sw=360&sh=360",
    description: "Flaunt your classy side with the help of this link chain, crafted in 22 karat yellow gold",
    price: "₹29175",
    starRating: 3.5,
    category: "Finger rings",
    metalType: "Gold",
    inStock: true,
  },
  {
    _id: "42294480526",
    title: "Regal Diamond Ring in Platinum",
    imgSrc: "https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwf43c3385/images/hi-res/74D2D2FSPAA02_1.jpg?sw=360&sh=360",
    description: "Flaunt your classy side with the help of this link chain, crafted in 22 karat yellow gold",
    price: "₹27556",
    starRating: 5,
    category: "Finger rings",
    metalType: "Diamond",
    inStock: true,
  },
  {
    _id: "77447485808",
    title: "Two Hearts Ring",
    imgSrc: "https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw84980580/images/hi-res/51D3B1FXAAA00_1.jpg?sw=360&sh=360",
    description: "Flaunt your classy side with the help of this link chain, crafted in 22 karat yellow gold",
    price: "₹18139",
    starRating: 3.5,
    category: "Finger rings",
    metalType: "Gold",
    inStock: false,
  },
  {
    _id: "45753443349",
    title: "Bold Diamond Ring in Platinum",
    imgSrc: "https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw47ba5033/images/hi-res/749992FDDAA02_1.jpg?sw=360&sh=360",
    description: "Flaunt your classy side with the help of this link chain, crafted in 22 karat yellow gold",
    price: "₹59378",
    starRating: 5,
    category: "Finger rings",
    metalType: "Diamond",
    inStock: true,
  },
  {
    _id: "78637589529",
    title: "Brihadeeswarar temple 8 gram Gold Coin",
    imgSrc: "https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw813b056c/images/hi-res/60C2ECZAPAAP00_1.jpg?sw=360&sh=360",
    description: "Flaunt your classy side with the help of this link chain, crafted in 22 karat yellow gold",
    price: "₹50755",
    starRating: 5,
    category: "Gold chain",
    metalType: "Gold",
    inStock: false,
  },
  {
    _id: "75722721983",
    title: "Balaji 5 gram Gold Coin",
    imgSrc: "https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwfd906ab7/images/hi-res/600745ZAAABP00_1.jpg?sw=360&sh=360",
    description: "Flaunt your classy side with the help of this link chain, crafted in 22 karat yellow gold",
    price: "₹31431",
    starRating: 2,
    category: "Gold chain",
    metalType: "Gold",
    inStock: true,
  },
  {
    _id: "84939624082",
    title: "Happy Anniversary Gold Coin",
    imgSrc: "https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwa5eda20c/images/hi-res/60C2DTZAGAAP00_1.jpg?sw=360&sh=360",
    description: "Flaunt your classy side with the help of this link chain, crafted in 22 karat yellow gold",
    price: "₹25389",
    starRating: 1,
    category: "Gold chain",
    metalType: "Gold",
    inStock: false,
  },
  {
    _id: "90949757560",
    title: "Edgy Floral Gold Stud Earrings for Kids",
    imgSrc: "https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw15d51c98/images/hi-res/51F1D1SEXAGACZ_1.jpg?sw=360&sh=360",
    description: "Flaunt your classy side with the help of this link chain, crafted in 22 karat yellow gold",
    price: "₹21832",
    starRating: 4,
    category: "Earrings",
    metalType: "Gold",
    inStock: true,
  },
  {
    _id: "810914465",
    title: "Contemporary Floral Stud Earrings",
    imgSrc: "https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw97df845c/images/hi-res/51D3B1SSBABACZ_1.jpg?sw=360&sh=360",
    description: "Flaunt your classy side with the help of this link chain, crafted in 22 karat yellow gold",
    price: "₹23006",
    starRating: 3,
    category: "Earrings",
    metalType: "Gold and Diamond",
    inStock: true,
  },
  {
    _id: "6404175218",
    title: "Double Circlet Gold and Diamond Stud Earrings",
    imgSrc: "https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw36c1f55c/images/hi-res/502995SQDAGA09_1.jpg?sw=360&sh=360",
    description: "Flaunt your classy side with the help of this link chain, crafted in 22 karat yellow gold",
    price: "₹24620",
    starRating: 4,
    category: "Earrings",
    metalType: "Gold and Diamond",
    inStock: true,
  },
  {
    _id: "74319029854",
    title: "Suave Fancy Seashell Stud Earrings",
    imgSrc: "https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw05eedaf5/images/hi-res/511920SBOABA00_1.jpg?sw=360&sh=360",
    description: "Flaunt your classy side with the help of this link chain, crafted in 22 karat yellow gold",
    price: "₹26242",
    starRating: 2,
    category: "Earrings",
    metalType: "Gold",
    inStock: false,
  },
  {
    _id: "41602578990",
    title: "The Butterfly Effect Diamond Pendant",
    imgSrc: "https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw035a89c2/images/hi-res/50D3FFPALAAA02_1.jpg?sw=360&sh=360",
    description: "Like the fluttering wings of a butterfly catching the golden sunshine, this radiant pendant is perfect for the free-spirited woman!",
    price: "₹73591",
    starRating: 5,
    category: "Pendants",
    metalType: "Diamond",
    inStock: true,
  },
  {
    _id: "69551858743",
    title: "Lovely Jitiya Pendant",
    imgSrc: "https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw61b1eacd/images/hi-res/51F2JPPGBAAA00_1.jpg?sw=360&sh=360",
    description: "Celebrate the auspicious day of jitiya with the radiance of thislovely pendant, crafted in 22 karat yellow gold",
    price: "₹27470",
    starRating: 4,
    category: "Pendants",
    metalType: "Gold",
    inStock: true,
  },
  {
    _id: "6685556516",
    title: "Majestic Jitiya Pendant",
    imgSrc: "https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw70ec243d/images/hi-res/51F2JPPGDAAA00_1.jpg?sw=360&sh=360",
    description: "Celebrate the auspicious day of jitiya with the radiance of this mesh pattern pendant, crafted in 22 karat yellow gold",
    price: "₹23002",
    starRating: 2,
    category: "Pendants",
    metalType: "Gold",
    inStock: true,
  },
  {
    _id: "91627295926",
    title: "Golden Grooves Diamond Pendant",
    imgSrc: "https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw2c8c2fe4/images/hi-res/50D3FFPAMAAA02_1.jpg?sw=360&sh=360",
    description: "Amuse everyone with the aurous swirl of this pendant, flecked with shimmering diamonds that cast a hypnotic charm!",
    price: "₹53781",
    starRating: 4,
    category: "Pendants",
    metalType: "Diamond",
    inStock: false,
  },
  {
    _id: "93709025118",
    title: "Spiral of Romance Diamond Pendant",
    imgSrc: "https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw92de8e98/images/hi-res/50D3FFPANAAA02_1.jpg?sw=360&sh=360",
    description: "Sail through your journey of love and romance with this heart pendant, gilded in gold and embedded with shiny diamonds!",
    price: "₹55136",
    starRating: 5,
    category: "Pendants",
    metalType: "Gold and Diamond",
    inStock: true,
  },
  {
    _id: "70004070960",
    title: "Charming Figaro Platinum Chain",
    imgSrc: "https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwa58d3c83/images/hi-res/74D3B3CTZAA00_1.jpg?sw=360&sh=360",
    description: "Be a sophisticated presence when you adorn this charming, Figaro pattern chain crafted in 950 platinum",
    price: "₹52983",
    starRating: 4,
    category: "Chains",
    metalType: "Platinum",
    inStock: true,
  },
  {
    _id: "363854602",
    title: "Contemporary Platinum Chain",
    imgSrc: "https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw27264dde/images/hi-res/74D3B3CUHAA00_1.jpg?sw=360&sh=360",
    description: "Radiate a contemporary charm with your style when you adorn this glittery chain, crafted in 950 platinum",
    price: "₹35272",
    starRating: 2,
    category: "Chains",
    metalType: "Platinum",
    inStock: false,
  },
  {
    _id: "13640021483",
    title: "Classy Link Chain",
    imgSrc: "https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw66a1f2ab/images/hi-res/51D3A1CNLAA00_1.jpg?sw=360&sh=360",
    description: "Flaunt your classy side with the help of this link chain, crafted in 22 karat yellow gold",
    price: "₹29199",
    starRating: 1,
    category: "Chains",
    metalType: "Gold",
    inStock: true,
  },
  {
    _id: "61352566116",
    title: "Delicate Loop and Bead Chain",
    imgSrc: "https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw92de8e98/images/hi-res/50D3FFPANAAA02_1.jpg?sw=360&sh=360",
    description: "A delicate loop and bead pattern makes this enticing chain, crafted in 22 karat yellow gold",
    price: "₹83871",
    starRating: 5,
    category: "Chains",
    metalType: "Gold",
    inStock: true,
  },
  {
    _id: "75439732160",
    title: "Enchanted Forest Diamond Bangle",
    imgSrc: "https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw546f2e6c/images/hi-res/50D3FFVAR1A02_1.jpg?sw=360&sh=360",
    description: "Adorn the beauty of nature on your wrist with this bangle, which captures the grace and movement of a butterfly!",
    price: "₹70642",
    starRating: 5,
    category: "Bangles",
    metalType: "Diamond",
    inStock: false,
  },
  {
    _id: "30150464067",
    title: "Delightful Ornate Bangle",
    imgSrc: "https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw83aea826/images/hi-res/51W2SAVDX1AP3_1.jpg?sw=360&sh=360",
    description: "Decadent in style and complete with a floral pattern this bangle is crafted in 22 karat yellow gold",
    price: "₹248932",
    starRating: 5,
    category: "Bangles",
    metalType: "Gold",
    inStock: true,
  },
  {
    _id: "10532904495",
    title: "Subtle Sparkle Bangle",
    imgSrc: "https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw1fcf3aa3/images/hi-res/51D3B2VBF1ACZ_1.jpg?sw=360&sh=360",
    description: "Add a subtle elegance to your style with the sparkle of this bangle, crafted in 22 karat yellow gold, with cubic zirconia",
    price: "₹85973",
    starRating: 5,
    category: "Bangles",
    metalType: "Gold",
    inStock: false,
  },
  {
    _id: "19357800444",
    title: "Sumukhi Kundan Polki Bangle",
    imgSrc: "https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw3e9bdcb7/images/hi-res/50O2AKVAX2AP3_1.jpg?sw=360&sh=360",
    description: "This scintillating 18 karat yellow gold kada bangle with kundan polki, is inspired by the charming marigold flower found in the miniature paintings",
    price: "₹376189",
    starRating: 5,
    category: "Bangles",
    metalType: "Gold",
    inStock: true,
  },
  {
    _id: "72225754412",
    title: "Charming Dainty Mangalsutra",
    imgSrc: "https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dwd5709492/images/hi-res/51D3B2YCBAACZ_1.jpg?sw=360&sh=360",
    description: "Designed to symbolise the unique charm of your marriage, this mangalsutra is crafted in 22 Karat Yellow Gold with a glossy finish.",
    price: "₹44057",
    starRating: 1,
    category: "Mangalsutras",
    metalType: "Gold",
    inStock: true,
  },
  {
    _id: "35432936573",
    title: "Radiant Flower Diamond Mangalsutra",
    imgSrc: "https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw691b06dc/images/hi-res/50D2J1YLRAA32.jpg?sw=360&sh=360",
    description: "Mark the beginning of a new journey with this radiant flower mangalsutra crafted in 18 karat rose gold, studded with diamonds. Stone Clarity: SI2",
    price: "₹50817",
    starRating: 5,
    category: "Mangalsutras",
    metalType: "Diamond",
    inStock: true,
  },
  {
    _id: "66105712119",
    title: "Elegant Nature Diamond Mangalsutra",
    imgSrc: "https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw1b33c524/images/hi-res/50D3PTYKJAA29_1.jpg?sw=360&sh=360",
    description: "The beauty of nature forms the inspiration for this lovely mangalsutra crafted in 18 karat yellow gold, studded with diamonds. Stone Clarity: I1/I2",
    price: "₹42571",
    starRating: 5,
    category: "Mangalsutras",
    metalType: "Diamond",
    inStock: false,
  },
  {
    _id: "50058743345",
    title: "Delicate Drop Diamond Pendant with Chain and Earrings Set",
    imgSrc: "https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw2239bd16/images/hi-res/50D2P20THEAA02_1.jpg?sw=360&sh=360",
    description: "The beauty of nature forms the inspiration for this lovely mangalsutra crafted in 18 karat yellow gold, studded with diamonds. Stone Clarity: I1/I2",
    price: "₹92529",
    starRating: 5,
    category: "Pendant Sets",
    metalType: "Gold",
    inStock: true,
  },
  {
    _id: "13270040952",
    title: "Rhombic Shape Diamond Pendant and Earrings Set",
    imgSrc: "https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw9616e073/images/hi-res/5032131ENABB02_1.jpg?sw=360&sh=360",
    description: "Take up your everday look up a notch with this Rhombic Shape Diamond Pendant and Earrings Set crafted in 18 Karat Gold. Stone clarity SI2.",
    price: "₹95714",
    starRating: 4,
    category: "Pendant Sets",
    metalType: "Gold",
    inStock: true,
  },
  {
    _id: "48745712955",
    title: "Radiant Pendant and Earrings Set",
    imgSrc: "https://www.tanishq.co.in/dw/image/v2/BKCK_PRD/on/demandware.static/-/Sites-Tanishq-product-catalog/default/dw21661110/images/hi-res/5029131CCABB02_1.jpg?sw=360&sh=360",
    description: "Illuminate your party ensembles with the radiance of this pendant and earrings set, crafted in 18 karat yellow gold, studded with diamonds. Stone Clarity: SI1/SI2",
    price: "₹160238",
    starRating: 1,
    category: "Pendant Sets",
    metalType: "Gold",
    inStock: false,
  },
];
